### PR TITLE
chore: bumping dependencies

### PR DESCRIPTION
**Pull request by kjappelbaum**

### CODE REVIEW

**Comment by targos** [comment]
can you please generate the package-lock using npm6/node14 ?

**Comment by kjappelbaum** [comment]
thanks for giving it a look 👍🏽 , it now uses `lockfileVersion: 1`

**Comment by targos** [comment]
have you tested that the `copy-views.js` script still works with the new version of nano?

**Comment by kjappelbaum** [comment]
i spun up the docker compose yesterday and it was fine but I'll test it again. I can also look into making a PR that adds some CI

**Comment by kjappelbaum** [comment]
the CI pipeline draft is in https://github.com/cheminfo/roc-eln-docker/pull/30

**Pull request merged**
